### ISSUE TITLE
movie details roadmap

### ISSUE THREAD

**Issue by ddanielsantos** [ddanielsantos/cloneboxd#48]
- [ ] a query returning movie stats to use in charts should be created
- [ ] reviews should have like and comment functionalities
- [ ] the create review button should work properly (no need to search movie then review it, pass the id directly)
- [ ] Recent/Top reviews sections should have a button to see a paginated list of the corresponding query
