### ISSUE TITLE
profile details roadmap

### ISSUE THREAD

**Issue by ddanielsantos** [ddanielsantos/cloneboxd#49]
- [ ] something like Instagram's profile page
  - [ ] change publications to reviews
  - [ ] change reels to lists
  - [ ] doesnt need the other two tabs
